name: DJKFOUR
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2973270497750491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030403'
    - '#ffffff'
    - '#d6e28b'
    - '#727553'
    - '#393939'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
